FROM node:18-alpine AS base

RUN npm i -g pnpm

FROM base AS deps

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

FROM base AS run

WORKDIR /app

COPY . .
COPY --from=deps /app/node_modules ./node_modules

EXPOSE 5173

RUN pnpm run dev
